# Generated by Django 3.0.5 on 2020-04-19 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200418_2255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='breaking',
        ),
    ]
