# Generated by Django 3.0.5 on 2020-04-23 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20200423_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='likes',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
