# Generated by Django 3.0.5 on 2020-04-24 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='team'),
        ),
    ]
